# Generated by Django 4.1 on 2022-08-26 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longtitude",
                    models.DecimalField(decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "altitude",
                    models.DecimalField(decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(1, "Busy"), (0, "Free")], default=0),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.CharField(max_length=100)),
                ("dest", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "TO_ASSIGN"), (1, "ASSIGNED"), (2, "DELIVERED")],
                        default=0,
                    ),
                ),
                ("isActive", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("assignedAt", models.DateTimeField(null=True)),
                ("deliveredAt", models.DateTimeField(null=True)),
                (
                    "assignedTo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uptime.driver",
                    ),
                ),
            ],
        ),
    ]
